【xpaas-flowcontrol-console】【author@wwx949895】【reviewer@WX949037 张虎】【02.18】【#98】 checkstyle修改
yihuabaowei/X-PaaS pull request #133
Opened 2021-02-18 06:52 UTC by wangxiaolong144

#98 
Description：空指针，变量顺序修改
Author:@wwx949895
Reviewer:@WX949037 张虎

2021-02-18 07:10 UTC, myfairys approved these changes
ok

2021-02-18 07:19 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +            return ruleEntityId(entity);
这块代码else这块是不是有些多余

2021-02-18 07:20 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> +            return ruleEntityId(entity);
同上，相同的代码提出来

2021-02-18 07:20 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperSystemControllerWrapper.java
> +            return ruleEntityId(entity);
同上

2021-02-18 07:21 UTC, 3838438abcd requested changes
见comment

2021-02-18 07:37 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +            return ruleEntityId(entity);
已修改

2021-02-18 07:54 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +        return ruleEntityId(entity);
return idLong;这块直接挪到最后，无需再次调用ruleEntityId

2021-02-18 07:57 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +        return ruleEntityId(entity);
null的时候需要调用ruleEntityId，这个是else的逻辑

2021-02-18 09:03 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +        return ruleEntityId(entity);
null的时候需要调用ruleEntityId，这个是else的逻辑

2021-02-18 09:03 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> +            return ruleEntityId(entity);
传递对象不一下，提不出来

2021-02-19 01:21 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +        return ruleEntityId(entity);
其实这里无非就是有两种情况，id为空或者id初始值为-1就会调用ruleEntityId重新生成，那你直接一个if判断就可以了  id == null || id ==  SystemUtils.LONG_INITIALIZE

2021-02-19 07:44 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +        return ruleEntityId(entity);
已修改

2021-02-19 08:20 UTC, merged