【PR】【transport、agent】【author@何帆】【reviewer@周升升】【0225】优化 transport，修改agent兼容zipkin的方法
yihuabaowei/X-PaaS pull request #168
Opened 2021-02-25 12:37 UTC by hefan-yb

【transport】优化消费kafka性能
【agent】修改exit的spanId，防止之前的方案出现相同的segmentId导致数据覆盖问题

2021-02-25 14:26 UTC, 3838438abcd commented on application-performance-management/apm-sniffer/apm-sdk-plugin/dubbo-2.7.x-plugin/src/main/java/com/huawei/apm/plugin/asf/dubbo/util/ZipKinUtil.java
> +     * @param span
注释加上

2021-02-25 14:30 UTC, 3838438abcd commented on application-performance-management/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/trace/AbstractTracingSpan.java
> +                    continue;
新的span id为什么可以直接覆盖，是否会影响链路关联

2021-02-25 14:34 UTC, 3838438abcd commented on application-performance-management/apm-sniffer/apm-sdk-plugin/dubbo-plugin/src/main/java/com/huawei/apm/plugin/dubbo/util/ZipKinUtil.java
>       * @param contextCarrier
注释同上

2021-02-25 14:36 UTC, 3838438abcd commented on application-performance-management/apm-sniffer/apm-sdk-plugin/dubbo-plugin/src/main/java/com/huawei/apm/plugin/dubbo/util/ZipKinUtil.java
>          rpcContext.getAttachments().put(Constant.ZIPKIN_SAMPLED, CheckSampler.checkDubboSampling(DubboThreadLocalSampling.getDubboSamplingFlag(), contextCarrier));
这一块代码与上面的zipkinutil的一块有什么区别么

2021-02-25 14:36 UTC, 3838438abcd commented on application-performance-management/apm-sniffer/apm-sdk-plugin/feign-default-http-9.x-plugin/src/main/java/com/huawei/apm/plugin/feign/http/v9/util/ZipKinUtil.java
> +     * @param span
注释，漏掉的都补充下

2021-02-25 14:38 UTC, 3838438abcd commented on application-performance-management/apm-sniffer/apm-sdk-plugin/spring-plugins/resttemplate-4.x-plugin/src/main/java/com/huawei/apm/plugin/spring/resttemplate/ZipKinUtil.java
>          httpRequest.getHeaders().set(Constant.ZIPKIN_SPAN_ID, String.valueOf(contextCarrier.getSpanId()));
和同步的比较，这里的spanid为什么不是上游生成的？

2021-02-25 14:39 UTC, 3838438abcd commented on application-performance-management/zipkin-transport/src/main/java/com/huawei/transport/consumer/SegmentSendScheduler.java
> +
去掉多余空行

2021-02-25 14:40 UTC, 3838438abcd commented on application-performance-management/zipkin-transport/src/main/java/com/huawei/transport/consumer/SegmentSendScheduler.java
> +    private final long delay = 2000;
单位注释

2021-02-25 14:40 UTC, 3838438abcd commented on application-performance-management/zipkin-transport/src/main/java/com/huawei/transport/consumer/SegmentSendScheduler.java
> +    private final long delay = 2000;
单位注释

2021-02-25 14:40 UTC, 3838438abcd commented on application-performance-management/zipkin-transport/src/main/java/com/huawei/transport/consumer/SegmentSendScheduler.java
> + * @date 2021-02-03
@date 改为since，描述也说明下

2021-02-25 14:40 UTC, 3838438abcd commented on application-performance-management/zipkin-transport/src/main/java/com/huawei/transport/consumer/SegmentSendScheduler.java
> +
去掉多余空行

2021-02-25 14:47 UTC, 3838438abcd commented on application-performance-management/zipkin-transport/src/main/java/com/huawei/transport/redis/RedisUtil.java
> +                if (isMark) {
result是否存在空指针问题？

2021-02-25 15:01 UTC, 3838438abcd commented on application-performance-management/zipkin-transport/src/main/java/com/huawei/transport/redis/RedisUtil.java
> +            return snapshot;
这一段新建map的意义是否可以解释下；新建map如果之间size，建议初始化的时候就给加上初始化容量，以免后续扩容耗时

2021-02-25 15:02 UTC, 3838438abcd requested changes
见comments

2021-02-26 01:35 UTC, hefan-yb commented on application-performance-management/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/trace/AbstractTracingSpan.java
> +                    continue;
这块修改是修复之前sw->zipkin传递的spanId，这个spanId在zipkin转换成segment时会用做segmentId，然后出现了重复的情况。后面就改成这个方式生成新的spanId来覆盖之前的spanId。已测试不影响链路

2021-02-26 02:26 UTC, 3838438abcd commented on application-performance-management/apm-sniffer/apm-sdk-plugin/dubbo-plugin/src/main/java/com/huawei/apm/plugin/dubbo/util/ZipKinUtil.java
>          rpcContext.getAttachments().put(Constant.ZIPKIN_INTERFACE, contextCarrier.getParentEndpoint());
下面这四行不能抽出来吗，和上面的也是一模一样的，依赖包不一样？

2021-02-26 02:32 UTC, hefan-yb commented on application-performance-management/apm-sniffer/apm-sdk-plugin/dubbo-plugin/src/main/java/com/huawei/apm/plugin/dubbo/util/ZipKinUtil.java
>          rpcContext.getAttachments().put(Constant.ZIPKIN_INTERFACE, contextCarrier.getParentEndpoint());
dubbo的两个插件的依赖版本不一样，不知道改了会不会有影响。

2021-02-26 02:40 UTC, 3838438abcd approved these changes
good

2021-02-26 02:43 UTC, merged