【PR】【支持慢调用和错误调用的链路采集】【author@zwx949037】【reviewer@wwx949895】【2021.01.07】【#24】提交慢/错误调用的链路采集的逻辑代码
yihuabaowei/X-PaaS pull request #25
Opened 2021-01-07 07:12 UTC by myfairys

Description [支持慢调用和错误调用的链路采集] [#24 ] 提交慢/错误调用的链路采集相关的逻辑代码 

Author:@zwx949037 张虎 
Reviewer:@wwx949895 王小龙

2021-01-07 08:01 UTC, wangxiaolong144 approved these changes
okey

2021-01-07 08:23 UTC, wangxiaolong144 approved these changes

2021-01-07 08:23 UTC, wangxiaolong144 commented on applications-manager/apm-sniffer/apm-agent-core/src/main/java/com/huawei/apm/agent/core/conf/DynamicConfig.java
>      }
为什么会有zipkin？

2021-01-07 08:24 UTC, myfairys commented on applications-manager/apm-sniffer/apm-agent-core/src/main/java/com/huawei/apm/agent/core/conf/DynamicConfig.java
>      }
已修改

2021-01-07 09:39 UTC, yangyshdan requested changes
如聊，功能没全部完成。需要将错误调用的标识传染到上游。请整改

2021-01-11 04:55 UTC, wangxiaolong144 approved these changes
okey

2021-01-11 11:35 UTC, wangxiaolong144 commented
good

2021-01-11 11:35 UTC, merged