【ui管控】【author@wwx949895】【reviewer@WX949037 张虎】【12.18】【#3】 新增规则逻辑修改
yihuabaowei/X-PaaS pull request #4
Opened 2020-12-18 05:42 UTC by wangxiaolong144

#3 
Description：新增规则，如果存在，提示用户
Author:@wwx949895
Reviewer:@WX949037 张虎

2020-12-18 06:33 UTC, beetle-man requested changes
按照检视意见修改一下

2020-12-18 06:33 UTC, beetle-man commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
>          return null;
返回null代表啥意思？成功还是失败？

2020-12-18 06:33 UTC, beetle-man commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperSystemControllerWrapper.java
> -        if (null != highestCpuUsage && highestCpuUsage > 1) {
87行已经使用了highestCpuUsage，这一行再判空？

2020-12-18 06:33 UTC, beetle-man commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> -
178在遍历里面remove会有concurrentModifyException的风险，改为迭代器的方式

2020-12-18 06:33 UTC, beetle-man commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> -
169对list的判空不严谨，没进行isEmpty判空，建议统一使用apache的commons-collection里的colletionUtil判空

2020-12-18 06:33 UTC, beetle-man commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> +        }
这堆事情可以在173-181的遍历里面一次性做完。

2020-12-18 06:33 UTC, beetle-man commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +        String id = entity.getApp() + ":" + entity.getIp() + ":" + entity.getPort() + ":" +
冒号使用这么频繁，提取个常量，叫“啥啥_SEPARATOR”

2020-12-18 06:33 UTC, beetle-man commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +            Result<String> getDate = getDate(ruleEntityList, id,null,null);
提交的代码注意格式化一下，缺少必要的空格

2020-12-18 06:33 UTC, beetle-man commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +            Result<DegradeRuleEntity> getDate = getDate(ruleEntityList, id,grade,entity);
参数前缺少空格，注意格式化

2020-12-18 06:56 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
>          return null;
null 表示成功，如果有错误会返回Result,ofFail

2020-12-18 06:58 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperSystemControllerWrapper.java
> -        if (null != highestCpuUsage && highestCpuUsage > 1) {
这是删除代码 -

2020-12-18 07:41 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> -
已修改

2020-12-18 08:20 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> -
已修改

2020-12-18 08:22 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> +        }
这里需要先拿到之前的规则，判断修改的规则与之前的规则是否有阈值类型修改，才会去判断这里。如果放上上一个循环，你不知道第几个才是之前的规则。

2020-12-18 08:32 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +        String id = entity.getApp() + ":" + entity.getIp() + ":" + entity.getPort() + ":" +
已修改

2020-12-18 08:33 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +            Result<String> getDate = getDate(ruleEntityList, id,null,null);
已修改

2020-12-18 08:33 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +            Result<DegradeRuleEntity> getDate = getDate(ruleEntityList, id,grade,entity);
已修改

2020-12-21 01:15 UTC, 3838438abcd requested changes
方法头注释需要规范下，每一个参数需要说明其意义，返回是什么，有异常时说明什么时候会抛该异常，类似下面的都修复下哈  
/**
     * 删除规则
     *
     * @param id
     * @param ruleId
     * @param app
     * @return
     */

2020-12-21 03:00 UTC, beetle-man approved these changes

2020-12-21 03:00 UTC, beetle-man commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> +        }
从你的逻辑看来：
1、先决条件是参数grade是否为null，为null直接返回null（为何不是Result.ofSuccess?）
2、两部分循环，第一个是为了找到id和参数id相等的实体的grade是否等于参数grade，相等的话也是直接返回null
3、不相等的话，只要在list里存在至少一个id和参数id不相等的实体，它的flowRuleEntityId等于参数entity的flowRuleEntityId，那么结果失败。
按照以上逻辑，那么可以写为：
...
if (grade == null) {
    return null;
}

boolean isGradeEquals = true;
boolean isflowEquals = true;
String entityRuleId = flowRuleEntityId(entity);
for(FlowRuleEntity ruleEntity : ruleEntityList) {
    if (id.equals(getId(ruleEntity))) {
	    if (ruleEntity.getGrade().equals(grade)) {
			return null;
		} else {
			isGradeEquals = false;
		}
	} else {
		if (isflowEquals && !entityRuleId.equals(flowRuleEntityId(ruleEntity)) {
		    isflowEquals = false;
		}
	}
	
	if (!isGradeEquals && !isflowEquals) {
		return fail...
	}
}

return null;

2020-12-21 03:00 UTC, beetle-man commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
>          return null;
好吧，返回对应的Result.oFSuccess方法最好，null不易于理解

2020-12-21 03:12 UTC, myfairys approved these changes
ok

2020-12-21 03:36 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol/src/main/java/com/huawei/flowcontrol/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> +        }
如果isGradeEquals 为false，还会在跑一次循环，判断是否有改规则。不是isGradeEquals 为false，就一定会有该规则存在。

2020-12-21 03:40 UTC, 3838438abcd approved these changes
good

2020-12-21 03:40 UTC, merged