【xpaas-flowcontrol-console】【author@wwx949895】【reviewer@WX949037 张虎】【01.28】【#98】 checkstyle
yihuabaowei/X-PaaS pull request #99
Opened 2021-01-28 01:01 UTC by wangxiaolong144

#98

2021-01-28 12:14 UTC, 3838438abcd requested changes
见comments

2021-01-28 12:14 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/DashboardApplication.java
>   */
添加author注解

2021-01-28 12:14 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/filter/LoginFilter.java
> +
这里版权都改为2020-2021把

2021-01-28 12:14 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/repository/metric/RedisMetriceRepository.java
>          }
set命名规范

2021-01-28 12:14 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/rule/DynamicRulePublisherExt.java
>   */
类头怎么还有param注解

2021-01-28 12:14 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/util/MD5Util.java
>          }
异常信息改为英文

2021-02-01 09:50 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/rule/DynamicRulePublisherExt.java
>   */
继承源码，源码带参数

2021-02-02 01:22 UTC, myfairys commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/discovery/RedisMachineDiscovery.java
> +
日志对象是否需要定义为常量并且命名大写

2021-02-02 01:25 UTC, myfairys commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/repository/metric/RedisMetriceRepository.java
同上

2021-02-02 06:30 UTC, myfairys approved these changes
ok

2021-02-04 09:31 UTC, myfairys approved these changes
ok

2021-02-04 09:34 UTC, myfairys commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/config/RedisConfig.java
> +
注释的代码

2021-02-04 09:35 UTC, myfairys commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/config/RedisConfig.java
> +            //.clientName(appName + "_lettuce")
同上

2021-02-04 09:40 UTC, myfairys commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/ZookeeperConfig.java
>              LOGGER.info("SkyWalking zookeeper address = {}", zookeeperclient);
这两个日志需要改一下，都是skywalking的

2021-02-04 09:50 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/ZookeeperConfig.java
>              LOGGER.info("SkyWalking zookeeper address = {}", zookeeperclient);
已修改

2021-02-04 09:50 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/config/RedisConfig.java
> +            //.clientName(appName + "_lettuce")
已删除

2021-02-04 09:53 UTC, myfairys commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperFlowControllerWrapper.java
> +            + entity.isClusterMode();
可以用String.join方法简化一下

2021-02-04 11:09 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/ZookeeperConfig.java
> +            LOGGER.error("create zookeeper session failed. address: {}", zookeeperclient);
这个两块日志怎么重复打印

2021-02-04 11:12 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +                return Result.ofFail(SystemUtils.ERROR_CODE, ruleExists);
这个修改提示用原来的是否更好

2021-02-04 11:13 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
>              LOGGER.info("Failed to modify rule!");
这里可以打印相关的错误提示，只是说修改失败，不能定位问题

2021-02-04 11:14 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +                    return Result.ofFail(SystemUtils.ERROR_CODE, ruleExists);
同上ruleExists

2021-02-04 11:22 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
>              LOGGER.info("Failed to modify rule!");
已修改

2021-02-04 11:23 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +                return Result.ofFail(SystemUtils.ERROR_CODE, ruleExists);
重复字符串，checkstyle过不了

2021-02-04 11:23 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/ZookeeperConfig.java
> +            LOGGER.error("create zookeeper session failed. address: {}", zookeeperclient);
内容不一样，已修改

2021-02-04 11:23 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/datasource/entity/rule/zookeeper/controller/ZookeeperDegradeControllerWrapper.java
> +                    return Result.ofFail(SystemUtils.ERROR_CODE, ruleExists);
重复字符串，checkstyle过不了

2021-02-04 12:03 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/rule/DynamicRuleProviderExt.java
> + * @param <T>
这个参数去掉

2021-02-04 12:05 UTC, 3838438abcd commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/rule/DynamicRulePublisherExt.java
>   */
继承泛型源码也不需要把这个泛型写出来吧，没有什么意义

2021-02-04 12:06 UTC, 3838438abcd requested changes
几处日志和注释修改

2021-02-05 05:45 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/rule/DynamicRulePublisherExt.java
>   */
下面方法有使用  T rules
void publish(String app, String entityType, T rules) throws Exception;

2021-02-05 05:53 UTC, wangxiaolong144 commented on flowcontrol/flowcontrol-console/src/main/java/com/huawei/flowcontrol/console/rule/DynamicRuleProviderExt.java
> + * @param <T>
已修改

2021-02-05 06:54 UTC, 3838438abcd approved these changes
good

2021-02-05 06:55 UTC, merged